### ISSUE TITLE
Action equivalent for the rule in the docs for adding roles to the token

### ISSUE THREAD

**Issue by jbaynhamuk** [auth0/auth0-aspnetcore-authentication#104]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-aspnetcore-authentication#readme) and the [Examples](https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-aspnetcore-authentication/api/Auth0.AspNetCore.Authentication.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-aspnetcore-authentication/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am currently trying to use the roles defined with Auth0 user management in my Razor pages based web app. There is an Action sample provided in the admin website for adding roles to the token, but seemingly not in the format required by ASP.net. You provide a Rule to do this in https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md#roles, but I am under the impression that we shouldn't be using rules any more. 

### Describe the ideal solution

Could you rewrite the rule to be an Action?

**Comment by jbaynhamuk** [comment]
```
exports.onExecutePostLogin = async (event, api) => {
  const assignedRoles = (event.authorization || {}).roles;
  
  if (event.authorization) {
    api.idToken.setCustomClaim('http://schemas.microsoft.com/ws/2008/06/identity/claims/role', assignedRoles);
    api.accessToken.setCustomClaim('http://schemas.microsoft.com/ws/2008/06/identity/claims/role', assignedRoles);
  }
}
```
would appear to work as an Action equivalent

**Comment by frederikprijck** [comment]
Thanks, I opened a PR to update that snippet to use actions. Thanks!
