### ISSUE TITLE
.NET Standard 2 Support

### ISSUE THREAD

**Issue by InteXX** [auth0/auth0-aspnetcore-authentication#128]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-aspnetcore-authentication#readme) and the [Examples](https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-aspnetcore-authentication/api/Auth0.AspNetCore.Authentication.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-aspnetcore-authentication/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Need .NET Standard 2 support

### Describe the ideal solution

I'm building my application using .NET 8, and so for future-proofing purposes I need support for .NET Standard 2. Will this be feasible?

**Comment by frederikprijck** [comment]
Can you explain why you think you need support for .NET standard? What stops u from using the SDK as is with .NET 8?

**Comment by InteXX** [comment]
I was able just now to install the latest package in my .NET 8 project, which surprised me. Given that your documentation states ([here](https://github.com/auth0/auth0-aspnetcore-authentication#requirements)) that only .NET 6 and .NET 7 are supported, as well as your [NuGet page](https://www.nuget.org/packages/Auth0.AspNetCore.Authentication), I didn't expect that I'd be able to do so.

I haven't actually tried to use it, though, so that may bring some surprises. I don't know.

At any rate to answer your question: "Can you explain why you think you need support for .NET standard?" As mentioned, I'd like to 'future-proof' my application, so that I can update the project's target framework without delay at any point in the future.

**Comment by frederikprijck** [comment]
I think you do not need .NET Standard for that, as you have noticed. The mention in our README predates the release of .NET 8, and our SDK should work fine with .NET8 projects.

Closing, as everything works as expected.

**Comment by InteXX** [comment]
> I think you do not need .NET Standard for that

Actually, I do. To clarify: I need to be able, in the future, to update my project's target framework to e.g. .NET 9 or 10, without having to wait for explicit framework support by the Auth0 package. .NET Standard addresses this problem.

I believe it's too soon to close this issue. True, the package successfully installs in a .NET 8 project, but that's only a small part of the equation. Has the code been fully tested under .NET 8?

**Comment by frederikprijck** [comment]
According to https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-5-and-net-standard, it makes sense to not go to .NET Standard, but stick to .NET (currently we use 6, but they recommend using 8).

> If you don't need to support .NET Framework, you could go with .NET Standard 2.1 or .NET 8. We recommend you skip .NET Standard 2.1 and go straight to .NET 8. Most widely used libraries will multi-target for both .NET Standard 2.0 and .NET 5+. Supporting .NET Standard 2.0 gives you the most reach, while supporting .NET 5+ ensures you can leverage the latest platform features for customers that are already on .NET 5+.

Reading the above, I believe it makes sense to not target .NET Standard.

There is also a section on the downsides of .NET Standard:

> Here are some problems with .NET Standard that help explain why .NET 5 and later versions are the better way to share code across platforms and workloads

Even more so, you can see that the main library we rely on, also does not support .NET Standard: https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect

> Has the code been fully tested under .NET 8?

No, but neither would it if we ship .NET Standard. However, .NET does guarantee it should work, just as .NET standard does for when you want to support .NET Framework as well.

**Comment by InteXX** [comment]
Very good. Thank you for looking that up. That was an interesting read.

Do you have any ETA for the addition of a .NET 8 target?
