### ISSUE TITLE
The character '#' is getting encoded twice

### ISSUE THREAD

**Issue by jackabouaad** [auth0/auth0-aspnetcore-authentication#133]
### Checklist

- [X] The issue can be reproduced in the [auth0-aspnetcore-authentication sample app](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/tree/master/Quickstart/Sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-aspnetcore-authentication#readme) and the [Examples](https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-aspnetcore-authentication/api/Auth0.AspNetCore.Authentication.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-aspnetcore-authentication/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When specifying the CallbackPath in Auth0WebAppOptions upon adding the Auth0WebAppAuthentication to DI, the Uri encoding mechanism seems to be encoding the character '#' twice as I get the following **http%3A%2F%2Flocalhost%3A3000%2F%2523%2Fcallback** instead of **http%3A%2F%2Flocalhost%3A3000%2F%23%2Fcallback**.

### Reproduction

Inject Auth0WebAppAuthentication as follows:

```csharp
builder.Services.AddAuth0WebAppAuthentication(options =>
    {
        options.Domain = builder.Configuration["Auth0:Domain"];
        options.ClientId = builder.Configuration["Auth0:ClientId"];
        options.CallbackPath = "/#/callback";
    });
```

### Additional context

For clarification:

```python
>>> from urllib.parse import quote
>>> quote('#')
'%23'
>>> quote(quote('#'))
'%2523'
```

### auth0-aspnetcore-authentication version

1.4.0

### .NET version

8.0

**Comment by frederikprijck** [comment]
Can you help me understand the use-case? This SDK is supposed to be used in a web app, and the callback path is supposed to be a server-side route, not a client side.

**Comment by jackabouaad** [comment]
On Auth0, I have localhost:3000/#/callback whitelisted, but the request being sent to my auth0 domain has the redirect_uri query parameter with the wrong encoding of the '#' character.

**Comment by frederikprijck** [comment]
That does not realy answer my question. I understand the issue at hand, but I am not sure I understand the use-case.

When using this SDK, the redirect URI should be server-side, not client side.

**Comment by frederikprijck** [comment]
Closing as there was no more reply.
