### ISSUE TITLE
AddAuth0WebAppAuthentication does not expose all OpenIdConnect options, like SignInScheme

### ISSUE THREAD

**Issue by pergardebrink** [auth0/auth0-aspnetcore-authentication#134]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-aspnetcore-authentication#readme) and the [Examples](https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-aspnetcore-authentication/api/Auth0.AspNetCore.Authentication.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-aspnetcore-authentication/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The AddAuth0WebAppAuthentication method on the Authenticationbuilder extension does not expose all OpenIdConnect options needed in the Auth0WebOptions. Like the SignInScheme. 

If we want to use a different signin scheme for Auth0 that is not the default one, we cannot specify this (in our case, we are looking at setting up a "temp scheme" we use for claims transformation and other operations before signing in with the default (cookie) scheme.

### Describe the ideal solution

Either all the OpenIdConnectOptions are exposed in Auth0WebOptions (by inheritance although breaking change, would be one way), or that the SignInScheme is exposed explicitly on the 

### Alternatives and current workarounds

We have currently solved this by adding the following code to override the OpenIdConnectOptions setup by adding the following lines after the AddAuth0WebAppAuthentication is called:
```
services.Configure<OpenIdConnectOptions>(Auth0Constants.AuthenticationScheme, options => {
      options.SignInScheme = "AnotherSchemeForSignIn";
});
```

### Additional context

I can provide a PR for this. 

My suggestion would in this case be to simply expose at least the SignInScheme and possibly the other schemes available here: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions?view=aspnetcore-8.0

**Comment by frederikprijck** [comment]
I don't think it's neccesary for our SDK to expose every property, and the workaround you mention is expected.

I think we should try and focus on exposing the properties that cover the majority of use-cases, and have the other use `services.Configure<OpenIdConnectOptions>()` instead.

Closing, as I think this is already possible. If you believe this is not correct, let me know and happy to review a PR in that case.

**Comment by CasperWSchmidt** [comment]
@frederikprijck It might not be necessary to expose ALL properties, but it would surely be a nice thing to have to stay compliant with the functionality you wrap. 
Anyway, we're finding ourselves in a similar situation. We need one scheme for cookies internally in our application but a remote scheme (like Auth0) for the challenge (we do some mapping between the schemes). To make this work we need SignInScheme and/or ForwardSignIn. I'll create a PR adding these since they are pretty essential to use cases like this, which I believe are pretty common.
