### ISSUE TITLE
LoginParameters not working?

### ISSUE THREAD

**Issue by wp55** [auth0/auth0-aspnetcore-authentication#141]
### Checklist

- [X] The issue can be reproduced in the [auth0-aspnetcore-authentication sample app](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/tree/master/Quickstart/Sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-aspnetcore-authentication#readme) and the [Examples](https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-aspnetcore-authentication/api/Auth0.AspNetCore.Authentication.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-aspnetcore-authentication/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm not sure if it's a problem in this component or in Auth0 Actions? I'm adding an extra parameter "test_parameter" to send to the authorize endpoint with LoginParameters. But in the Auth0 Actions, that parameter is always missing in event.request.query.

### Reproduction

This is the code from the startup file:

![afbeelding](https://github.com/auth0/auth0-aspnetcore-authentication/assets/87134268/368dcc64-bc0a-48a4-9fb9-15c1073feaf8)

I'm sending an extra parameter "test_parameter" with value = true.

In Auth0 Actions, I've a post login action where I want to use that parameter. I've added some extra logging in order to check the incoming message:

![afbeelding](https://github.com/auth0/auth0-aspnetcore-authentication/assets/87134268/8d2ecd9f-83ec-4b5d-aab1-67be828e1feb)

But the parameter "test_parameter" is always missing in the incoming event:

![afbeelding](https://github.com/auth0/auth0-aspnetcore-authentication/assets/87134268/d61e0616-cf6e-4865-881d-e27dafec841d)

The second parameter "ui_locales" is working, I'm seeing the login screen in Dutch.

### auth0-aspnetcore-authentication version

1.4.1

### .NET version

6

**Comment by kailash-b** [comment]
Hi @wp55 
Thanks for reaching out. 
We did try this from our end and we are able to access extra parameters in Actions. 

Can you try to access the parameter directly like below 
`console.log('test_parameter : ' + JSON.stringify(event.request.query["test_parameter"]));`

There are a few limitations with the Actions, like the one regarding how much can be stored on the console.log().
It could be one reason why you are not seeing the value in your logs. 
You can read more about the limitations [here](https://auth0.com/docs/customize/actions/limitations)

Do reach out to us in case you need more support.
Thanks!

**Comment by kailash-b** [comment]
@wp55 If you are still facing issues, please feel free to re-open this issue. 
Closing the issue for now.
