### ISSUE TITLE
Allow Specifying Cookie Authentication Options

### ISSUE THREAD

**Issue by bbrandt** [auth0/auth0-aspnetcore-authentication#54]
### Describe the problem you'd like to have solved

I am using a subdomain per tenant model for my app, but I'd like my auth cookie to be shared across all subdomains to improve the experience for users that are members of multiple tenants and can switch between the different tenants.

### Describe the ideal solution

Allow `Action<CookieAuthenticationOptions>? configureCookieAuthenticationOptions` to be passed into `AddAuth0WebAppAuthentication()` like this:
https://github.com/AzureAD/microsoft-identity-web/blob/0e8a08d8c55edf3aec695a809d189d2ac4b770d9/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L247

This is how I accomplished what I was looking for with Microsoft.Identity.Web:
```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                    {
                        _configuration.Bind("AzureAd", options);
                        options.Events ??= new OpenIdConnectEvents();
                    },
                    cookieOptions =>
                    {
                        cookieOptions.Cookie.Domain = cookieDomain;
                        cookieOptions.Cookie.Path = "/";
                        cookieOptions.Cookie.SameSite = SameSiteMode.Lax;
                    });
```

## Alternatives and current work-arounds

I have not yet come up with a workaround to allow cookie to be shared across subdomains.

**Comment by bsheldrick** [comment]
I am able to configure the cookie like this...

`services.ConfigureApplicationCookie(options => // configure);`

**Comment by zgrose** [comment]
Thank you, @bsheldrick! I was looking to set the `ForwardDefaultSelector` for my mixed mode cookie/JWT site and your tip looks spot on!

**Comment by zgrose** [comment]
Follow-up to the above. ConfigureApplicationCookie will configure the `Identity.Application` authentication scheme which wouldn't help in my case but you sent me digging for more info I think mycorrect solution is to do something along these lines. Obviously I'm was doing something different than the OP, but this worked for my case. (.NET6 Program.cs):
````
builder.Services.AddOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme)
    .Configure( options => 
    {
        options.ForwardDefaultSelector = context =>
            context.Request.Path.StartsWithSegments(new PathString("/api"))   
              ? JwtBearerDefaults.AuthenticationScheme 
              : null;    
    });
````

**Comment by frederikprijck** [comment]
Apart from workarounds mentioned above, with the changes introduced in https://github.com/auth0/auth0-aspnetcore-authentication/pull/59 you can now also tell our SDK to not add the cookie middleware and take control of that part yourself:

```csharp
services
    .AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    })
    .AddCookie()
    .AddAuth0WebAppAuthentication(PlaygroundConstants.AuthenticationScheme, options =>
    {
        options.Domain = Configuration["Auth0:Domain"];
        options.ClientId = Configuration["Auth0:ClientId"];
        options.SkipCookieMiddleware = true;
    });
```
