### ISSUE TITLE
Add custom scheme support to AddAuth0WebAppAuthentication

### ISSUE THREAD

**Issue by pergardebrink** [auth0/auth0-aspnetcore-authentication#55]
### Describe the problem you'd like to have solved
When using AddAuth0WebAppAuthentication, it is currently only possible to setup a web application with a single Auth0 tenant and application. I would like the possibility to create multiple configuration with different schemes. 

### Describe the ideal solution
A possibility to define a custom scheme for a specific connection like the OpenIdConnect extension does: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.openidconnectextensions.addopenidconnect 
```
services.AddAuth0WebAppAuthentication(options => {
    options.ClientId = // secret for app1
    options.ClientSecret = // ... 
    options.Domain = // .. 
});

// One (or more) webapps
services.AddAuth0WebAppAuthentication("MyCustomScheme", options => {
    options.ClientId = // secret for app2
    options.ClientSecret = // ... 
    options.Domain = // .. 
});
```

### Alternatives and current work-arounds
I could work around this issue by using the OpenIdConnect provider directly to define several OpenId Connections, but the Auth0 library is very convenient and makes it much easier to define and use features like organization login parameter.

### Additional information, if any
If this is in line with the roadmap, but not planned in the near future, do you accept pull request for a feature like this?

**Comment by frederikprijck** [comment]
Thanks for this, this sounds like a valid request.

We definitely accept pull requests, if you are interested to implement this I would be mote than happy to review it!
