### ISSUE TITLE
Bump dependencies to .net 6

### ISSUE THREAD

**Issue by VictorioBerra** [auth0/auth0-aspnetcore-authentication#62]
### Describe the problem you'd like to have solved

Today we target the old 5.0.x versionof Microsoft.AspNetCore.Authentication.OpenIdConnect https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj#L9

### Describe the ideal solution

update TFM to net6.0, update dependencies

**Comment by frederikprijck** [comment]
I think that's fair, will see to bump it soon.

**Comment by npehrsson** [comment]
2 months ago, is it time yet?
