### ISSUE TITLE
Blazor role based Authentication

### ISSUE THREAD

**Issue by eliasstepanik** [auth0/auth0-aspnetcore-authentication#79]
Hello,
I tried using this package in blazor server but I ran into the issue that roles don´t seem to work.
Have you encountered this Problem before?
Is it possible to fix it?

**Comment by frederikprijck** [comment]
Hey, 
I am not aware of any specific issues, neither am I whether or not it would work. Can you elaborate on what's not working? Or even provide a reproduction sample so we can look into what's going on?

**Comment by eliasstepanik** [comment]
I followed this guide : "https://auth0.com/blog/what-is-blazor-tutorial-on-building-webapp-with-authentication/#Securing-the-Application-with-Auth0"
After I finished it I saw that I tried adding roles.
So I followed the guide your description but that didn't work.

**Comment by frederikprijck** [comment]
Can you elaborate on what you mean when you see it didn't work? As well as share a reproduction sample that shows how you are integrating it? Without that, it's going to be hard to understand what's happening.

**Comment by eliasstepanik** [comment]
Program.cs`
using Auth0.AspNetCore.Authentication;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using ManagmentInterface.Data;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();
builder.Services.AddAuth0WebAppAuthentication(options => {
    options.Domain = builder.Configuration["Auth0:Domain"];
    options.ClientId = builder.Configuration["Auth0:ClientId"];
});
builder.Services.AddRazorPages();


var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();`

**Comment by eliasstepanik** [comment]
`
@page "/"
@attribute [Authorize(Roles="Admin")]

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?"/>`

**Comment by eliasstepanik** [comment]
I added this to AUTH0 Rules:
function (user, context, callback) {
  const assignedRoles = (context.authorization || {}).roles;
  const idTokenClaims = context.idToken || {};

  idTokenClaims['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] = assignedRoles;

  context.idToken = idTokenClaims;

  callback(null, user, context);
}

**Comment by eliasstepanik** [comment]
When I try accessing the Page with a non Admin User.
I can still access it.

> @page "/" @Attribute [Authorize(Roles="Admin")]

**Comment by eliasstepanik** [comment]
Login and Logout wrok just fine

**Comment by frederikprijck** [comment]
Thanks for the information.

Can you please try and format your reply in such a way that it makes sense for anyone else reading it instead of spread out over several messages?

Can you verify the roles claim is actually present in the token? Can you also provide a runnable sample that demonstrates the behavior? 

Our SDK does not explicitly support Blazor, but it should work and I am happy to look into it if you can share a project for me to look into.

**Comment by eliasstepanik** [comment]
I created a Repo that contains an implementation like the one I used.
https://github.com/eliasstepanik/Auth0IntegrationTest

In Auth0 you have to set your Allowed Callback URLs to "https://localhost:7142/callback"
and your Allowed Logout URLs to "https://localhost:7142/"

I also created a Role that contains this Portion of code from your documentation.
`function (user, context, callback) {
  const assignedRoles = (context.authorization || {}).roles;
  const idTokenClaims = context.idToken || {};

  idTokenClaims['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] = assignedRoles;

  context.idToken = idTokenClaims;

  callback(null, user, context);
}`

**Comment by frederikprijck** [comment]
I cloned your repository, and once I ran it I can see the following when going to `/fetchdata`:

![image](https://user-images.githubusercontent.com/2146903/193826374-430cfc96-1077-4c56-a891-6ef65badc32d.png)

When I try with a user that does not have the `Admin` role, I get the following for the same `/fetchdata` endpoint:

![image](https://user-images.githubusercontent.com/2146903/193826590-b5d7625f-ae7a-4a85-a7ec-9e0b749f31cd.png)

So from the looks of it, everything works as expected. Important to remember that, whenever you change the roles, the user needs to logout and login again before the new roles take effect.

**Comment by eliasstepanik** [comment]
Thanks for YouTube answer could you share your auth0 config?

**Comment by frederikprijck** [comment]
What exactly do you mean when you say Auth0 config ?

**Comment by eliasstepanik** [comment]
Your Settings you added to your Auth0 Application.

**Comment by frederikprijck** [comment]
I used the same rule as you have, and I have ensured the user has the `Admin` role, so I can't realy tell what's going wrong on your end.
