### ISSUE TITLE
WithAccessToken Memory leak

### ISSUE THREAD

**Issue by jac0bbennett** [auth0/auth0-aspnetcore-authentication#80]
### Describe the problem
When using `.WithAccessToken`, the memory usage swells up on every refresh. If I remove `.WithAccessToken`, the memory usage and thread count is stable.

### Reproduction

```
builder.Services
    .AddAuth0WebAppAuthentication(options =>
    {
        options.Domain = builder.Configuration["Auth0:Domain"];
        options.ClientId = builder.Configuration["Auth0:ClientId"];
        options.ClientSecret = builder.Configuration["Auth0:ClientSecret"];

        options.Scope = "openid profile email";
    }).WithAccessToken(options =>
    {
        options.Audience = builder.Configuration["Auth0:Audience"];
        options.UseRefreshTokens = true;
});
```

### Environment

- **Version of `Auth0.AspNetCore.Authentication` used:** 1.0.3
- **Version of `.NET` used:** 6

**Comment by frederikprijck** [comment]
Thanks for reporting, I will look into this.

**Comment by frederikprijck** [comment]
Any chance you would have more information on what you noticed here @jac0bbennett ?

I have been profiling, and noticed the memory grows slightly, but I also noticed it's not different without enabling `WithAccessToken()`.

**Comment by jac0bbennett** [comment]
Yes, appears to be my same issue with the thread count rising every request. Appreciate you looking into it. Thanks @sjroesink as well.

**Comment by frederikprijck** [comment]
Closing the loop here, but please see https://github.com/auth0/auth0-aspnetcore-authentication/issues/86#issuecomment-1335859026 for more information about solving it for the time being.
