### ISSUE TITLE
Wrong redirect URL is used

### ISSUE THREAD

**Issue by dennisrahmen** [auth0/auth0-aspnetcore-authentication#87]
### Describe the problem

Using the SDK to secure my Blazor Server app based in this tutorial:
https://auth0.com/blog/what-is-blazor-tutorial-on-building-webapp-with-authentication/#Securing-the-Application-with-Auth0

Using this on my PC while debugging is working fine with "https://localhost:7299/" as the application URL and "https://localhost:7299/callback" as the callback URL.

Now I deployed the app and it is using "https://test-app-example.com/" but the callback URL is "http://test-app-example.com/callback" so plain HTTP not HTTPS, that results in a mismatch.

### What was the expected behavior?

The SDK should use the correct redirect URL, in my case using HTTPS not plain HTTP.

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of `Auth0.AspNetCore.Authentication` used:** 1.0.4
- **Version of `.NET` used:** v6.0.11
- **Other modules/plugins/libraries that might be involved:** None
- **Any other relevant information you think would be useful:** None

**Comment by frederikprijck** [comment]
If I understand correctly, the application is using HTTPS, but our SDK is using a HTTP URL to pass to Auth0, is that correct?

Do you use any reverse proxy or any specific set up to handle HTTPS as mentioned in this [SO question](https://stackoverflow.com/questions/62559600/set-openid-connect-callbackpath-to-https)?

If that's the case, it's likely an issue originating from that side and would investigate that side to ensure .NET knows you are using HTTPS to avoid additional issues.

**Comment by dennisrahmen** [comment]
Thanks for the help, that seems to be the case as when running locally the correct protocol is used.
