### ISSUE TITLE
Blazor Server WithAccessToken not working

### ISSUE THREAD

**Issue by gnamse** [auth0/auth0-aspnetcore-authentication#99]
When i use `.WithAccessToken` i get the forllowing error **Both Client Secret and Client Assertion can not be null when requesting an access token, one or the other has to be set.**

Reporduction
- Create a blazor server side application
- Add 
`builder.Services
    .AddAuth0WebAppAuthentication(options => {
        options.Domain = builder.Configuration["Auth0:Domain"];
        options.ClientId = builder.Configuration["Auth0:ClientId"];
        options.ClientSecret  = builder.Configuration["Auth0:ClientSecret"];
    })
    .WithAccessToken(options =>
    {
        options.Audience = builder.Configuration["Auth0:Audience"];
    });
`
**Version of Auth0.AspNetCore.Authentication used: 1.1.0
Version of .NET used: 6**

**Comment by frederikprijck** [comment]
Thanks for reaching out.

This error shows up when the ClientSecret is null or empty, or when the `ClientAssertionSecurityKey ` is null.

Are you sure there is a value set for ClientSecret that's not an empty string?

**Comment by gnamse** [comment]
When i copied my Auth0 config from **appsettings.Development.json** to **appsettings.json**, the error went away. It seems it was reading the config  from the wrong file.
